version: 1

style:
  field_naming: snake_case

date_time_spec:
  date_field: dates
  time_field: times
  date_format: "YYYY-MM-DD"
  time_format: "HH:mm"
  zip_rule: pairwise_equal_length
  timezone: local

validation:
  fail_fast: true
  error_on_missing_required_on_publish: true
  error_on_mismatched_dates_times_length: true

ontology:
  labels:
    - movie
    - book_club
    - concert
    - opera
    - dance
    - other

templates:
  movie:
    grouping: by_title
    fields:
      - title
      - dates
      - times
      - director
      - runtime_minutes
      - release_year
      - country
      - language
      - rating
      - one_liner_summary
      - description
      - url
      - venue
      - occurrences
    required_on_publish:
      - title
      - dates
      - times
      - rating
      - one_liner_summary
      - description
      - director
      - runtime_minutes
      - release_year
      - country
      - occurrences
    field_definitions:
      occurrences:
        type: array
        description: "Array of specific event occurrences. Generated from dates/times arrays."
        item_schema:
          type: object
          properties:
            date:
              type: string
              description: "Event date in YYYY-MM-DD format"
            time:
              type: string  
              description: "Event time (e.g., '11:00', '7:00 PM', 'TBD')"
            url:
              type: string
              description: "Source URL for this occurrence"
            venue:
              type: string
              description: "Venue name for this occurrence"
          required:
            - date
            - time
            - url
            - venue

  book_club:
    grouping: unique
    fields:
      - title
      - dates
      - times
      - book
      - author
      - publication_year
      - series
      - host
      - rating
      - one_liner_summary
      - description
      - url
      - venue
      - occurrences
    required_on_publish:
      - title
      - dates
      - times
      - rating
      - one_liner_summary
      - description
      - book
      - author
      - occurrences
    field_definitions:
      title:
        type: string
        description: "Format as '[Series Name] - [Book Title]' (e.g., 'NYRB Book Club - Nightmare Alley'). Extract the series name from headers and combine with the book title."
      book:
        type: string
        description: "ONLY the book title being discussed (e.g., 'Nightmare Alley'). Extract from patterns like 'Nightmare Alley by William Lindsey Gresham' - keep only the title part before 'by'."
      author:
        type: string
        description: "ONLY the author's name (e.g., 'William Lindsey Gresham'). Extract from patterns like 'Nightmare Alley by William Lindsey Gresham' - keep only the name part after 'by'."
      dates:
        type: array
        description: "Event dates in YYYY-MM-DD format. For dates without years: use current year for current month-December, use next year for January-current month."
      times:
        type: array
        description: "Meeting times in 24-hour format like '11:00' or '15:00'. Look for text like 'Meets the 1st Saturday of every month at 11am' in each book club section description."
      venue:
        type: string
        description: "The location where the book club meets (e.g., 'Alienated Majesty Books', 'First Light Books')."
      host:
        type: string
        description: "Organization running the book club (e.g., 'Austin NYRB Book Club', 'East Austin Writing Project'). Look for text like 'Run by [Organization Name]' in descriptions."
      description:
        type: string
        description: "Full description of the book club series. Include the tagline, meeting schedule, and organizer information."
      series:
        type: string
        description: "Book club series name exactly as shown in section headers (e.g., 'NYRB Book Club', 'Subculture Lit', 'A Season Of', 'Voyage Out', 'Apricot Trees Exist')."
      url:
        type: string
        description: "The source URL of the webpage where the event was found."
      publication_year:
        type: integer
        description: "The year the book was published."
      rating:
        type: float
        description: "Rating score for the event (1.0-5.0)."
      one_liner_summary:
        type: string
        description: "A brief, compelling summary of the book club event."
      occurrences:
        type: array
        description: "Array of specific event occurrences. Generated from dates/times arrays."
        item_schema:
          type: object
          properties:
            date:
              type: string
              description: "Event date in YYYY-MM-DD format"
            time:
              type: string  
              description: "Event time (e.g., '11:00', '7:00 PM', 'TBD')"
            url:
              type: string
              description: "Source URL for this occurrence"
            venue:
              type: string
              description: "Venue name for this occurrence"
          required:
            - date
            - time
            - url
            - venue

  concert:
    grouping: unique
    fields:
      - title
      - dates
      - times
      - program
      - series
      - featured_artist
      - composers
      - works
      - venue
      - rating
      - one_liner_summary
      - description
      - url
      - occurrences
    required_on_publish:
      - title
      - dates
      - times
      - rating
      - one_liner_summary
      - description
      - program
      - occurrences
    field_definitions:
      occurrences:
        type: array
        description: "Array of specific event occurrences. Generated from dates/times arrays."
        item_schema:
          type: object
          properties:
            date:
              type: string
              description: "Event date in YYYY-MM-DD format"
            time:
              type: string  
              description: "Event time (e.g., '11:00', '7:00 PM', 'TBD')"
            url:
              type: string
              description: "Source URL for this occurrence"
            venue:
              type: string
              description: "Venue name for this occurrence"
          required:
            - date
            - time
            - url
            - venue

  opera:
    grouping: unique
    fields:
      - title
      - dates
      - times
      - program
      - series
      - featured_artist
      - composers
      - works
      - venue
      - rating
      - one_liner_summary
      - description
      - url
      - occurrences
    required_on_publish:
      - title
      - dates
      - times
      - rating
      - one_liner_summary
      - description
      - program
      - occurrences
    field_definitions:
      occurrences:
        type: array
        description: "Array of specific event occurrences. Generated from dates/times arrays."
        item_schema:
          type: object
          properties:
            date:
              type: string
              description: "Event date in YYYY-MM-DD format"
            time:
              type: string  
              description: "Event time (e.g., '11:00', '7:00 PM', 'TBD')"
            url:
              type: string
              description: "Source URL for this occurrence"
            venue:
              type: string
              description: "Venue name for this occurrence"
          required:
            - date
            - time
            - url
            - venue

  dance:
    grouping: unique
    fields:
      - title
      - dates
      - times
      - program
      - series
      - venue
      - rating
      - one_liner_summary
      - description
      - url
      - occurrences
    required_on_publish:
      - title
      - dates
      - times
      - rating
      - one_liner_summary
      - description
      - program
      - occurrences
    field_definitions:
      occurrences:
        type: array
        description: "Array of specific event occurrences. Generated from dates/times arrays."
        item_schema:
          type: object
          properties:
            date:
              type: string
              description: "Event date in YYYY-MM-DD format"
            time:
              type: string  
              description: "Event time (e.g., '11:00', '7:00 PM', 'TBD')"
            url:
              type: string
              description: "Source URL for this occurrence"
            venue:
              type: string
              description: "Venue name for this occurrence"
          required:
            - date
            - time
            - url
            - venue

  other:
    grouping: unique
    fields:
      - title
      - dates
      - times
      - venue
      - rating
      - one_liner_summary
      - description
      - url
      - occurrences
    required_on_publish:
      - title
      - dates
      - times
      - rating
      - one_liner_summary
      - description
      - venue
      - occurrences
    field_definitions:
      occurrences:
        type: array
        description: "Array of specific event occurrences. Generated from dates/times arrays."
        item_schema:
          type: object
          properties:
            date:
              type: string
              description: "Event date in YYYY-MM-DD format"
            time:
              type: string  
              description: "Event time (e.g., '11:00', '7:00 PM', 'TBD')"
            url:
              type: string
              description: "Source URL for this occurrence"
            venue:
              type: string
              description: "Venue name for this occurrence"
          required:
            - date
            - time
            - url
            - venue

pipeline_defaults:
  classification:
    enabled: true
  enrichment:
    enabled: true
  scrape:
    frequency: daily   # daily | weekly | monthly | manual

field_defaults:
  rating: -1  # Unrated
  description: "No description available"
  country: "USA"
  language: "English"
  url: ""
  venue: ""

venues:
  afs:
    display_name: Austin Film Society
    scrape:
      enabled: true
      frequency: monthly
    classification:
      enabled: false
      assumed_event_category: movie
    enrichment:
      enabled: false

  hyperreal:
    display_name: Hyperreal
    scrape:
      enabled: true
      frequency: monthly
    classification:
      enabled: true
    enrichment:
      enabled: true

  paramount:
    display_name: Paramount
    scrape:
      enabled: true
      frequency: monthly
    classification:
      enabled: true
    enrichment:
      enabled: true

  alienated_majesty:
    display_name: Alienated Majesty (Book Clubs)
    scrape:
      enabled: true
      frequency: monthly
    classification:
      enabled: false
      assumed_event_category: book_club
    enrichment:
      enabled: true
    extraction:
      batch_description: "List of book club events extracted from Alienated Majesty Books webpage. Look for book club sections with headers like 'NYRB Book Club', 'Subculture Lit', 'A Season Of', 'Voyage Out', 'Apricot Trees Exist'. For each section, extract the book meetings listed under 'Upcoming Meetings'."
    field_overrides:
      venue:
        required: false
        description: "Always 'Alienated Majesty Books' for this website."
        default_value: "Alienated Majesty Books"
      series:
        required: true
        description_append: " This is REQUIRED - find which book club section each meeting belongs to."
      url:
        required: true
        description: "The source URL of the webpage"
      dates:
        dynamic_guidance: true  # Add date inference guidance at runtime
        description_append: " Examples: 'Saturday, October 4' → 'YYYY-10-04', 'Saturday, January 3' → 'YYYY-01-03'. Return as array of dates."

  first_light:
    display_name: First Light (Book Clubs)
    scrape:
      enabled: true
      frequency: monthly
    classification:
      enabled: false
      assumed_event_category: book_club
    enrichment:
      enabled: true

  austin_symphony:
    display_name: Austin Symphony
    scrape:
      enabled: true
      frequency: yearly
    classification:
      enabled: false
      assumed_event_category: concert
    enrichment:
      enabled: false

  early_music_austin:
    display_name: Early Music Austin
    scrape:
      enabled: true
      frequency: yearly
    classification:
      enabled: false
      assumed_event_category: concert
    enrichment:
      enabled: false

  la_follia:
    display_name: La Follia
    scrape:
      enabled: true
      frequency: yearly
    classification:
      enabled: false
      assumed_event_category: concert
    enrichment:
      enabled: false

  austin_chamber_music:
    display_name: Austin Chamber Music
    scrape:
      enabled: true
      frequency: yearly
    classification:
      enabled: false
      assumed_event_category: concert
    enrichment:
      enabled: false

  austin_opera:
    display_name: Austin Opera
    scrape:
      enabled: true
      frequency: yearly
    classification:
      enabled: false
      assumed_event_category: opera
    enrichment:
      enabled: false

  ballet_austin:
    display_name: Ballet Austin
    scrape:
      enabled: true
      frequency: yearly
    classification:
      enabled: false
      assumed_event_category: dance
    enrichment:
      enabled: false

  arts_on_alexander:
    display_name: Arts on Alexander
    scrape:
      enabled: false
      frequency: yearly
    classification:
      enabled: false
      assumed_event_category: concert
    enrichment:
      enabled: false


