name: Monthly Culture Calendar Update

on:
  schedule:
    # Run on the 1st of every month at 6 AM UTC (1 AM CST / 12 AM CDT in Austin)
    - cron: '0 6 1 * *'
  # Allow manual triggering for monthly updates
  workflow_dispatch:

permissions:
  contents: write

jobs:
  monthly-update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run monthly calendar update
      env:
        PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
      run: |
        echo "🗓️ Running monthly update - collecting full upcoming month of events"
        python update_website_data.py
        
    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action - Monthly Update"
        
    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git add docs/data.json docs/calendars/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "🗓️ Monthly calendar update - $(date -u +%B\ %Y)"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
        fi