name: Re-rate All Events

on:
  # Allow manual triggering only
  workflow_dispatch:

permissions:
  contents: write

jobs:
  re-rate-events:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Re-rate all events
      env:
        PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
      run: |
        echo "🎭 Re-rating all events - forcing fresh AI analysis"
        python update_website_data.py --full --force-reprocess
        
    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action - Re-rate Events"
        
    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git add docs/data.json docs/source_update_times.json
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "🎭 Re-rated all events with fresh AI analysis - $(date -u +%Y-%m-%d)"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
        fi